### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by royshau** [lrse/batch_ros#1]
Hi,

always nice to find out someone is after the same goal :)

i've tried inserting this in an existing workspace, but it will not build - 

displays all kind of c++17 errors (even though the cmakelists is definitely running.)

here is a snippet:

`/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp: In member function ‘void batch_ros::BagPlayer::play()’:
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:22: error: expected unqualified-id before ‘[’ token
           for (auto& [k,v] : *sent_states)
                      ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:22: error: expected ‘;’ before ‘[’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:23: error: ‘k’ was not declared in this scope
           for (auto& [k,v] : *sent_states)
                       ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp: In lambda function:
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:28: error: expected ‘{’ before ‘:’ token
           for (auto& [k,v] : *sent_states)
                            ^
In file included from /home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:2:0:
/opt/ros/kinetic/include/rosbag/view.h: In member function ‘void batch_ros::BagPlayer::play()’:
/opt/ros/kinetic/include/rosbag/view.h:163:5: error: ‘rosbag::View::View(const rosbag::View&)’ is private
     View(View const& view);
     ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:22: error: within this context
           for (auto& [k,v] : *sent_states)
                      ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:28: error: could not convert ‘<lambda closure object>batch_ros::BagPlayer::play()::<lambda()>{rosbag::View(v)}’ from ‘batch_ros::BagPlayer::play()::<lambda()>’ to ‘bool’
           for (auto& [k,v] : *sent_states)
                            ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:28: error: expected ‘;’ before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:28: error: expected primary-expression before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:28: error: expected ‘)’ before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:83:28: error: expected primary-expression before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:22: error: expected unqualified-id before ‘[’ token
           for (auto& [k,v] : *sent_states)
                      ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:22: error: expected ‘;’ before ‘[’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:23: error: ‘k’ was not declared in this scope
           for (auto& [k,v] : *sent_states)
                       ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp: In lambda function:
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:28: error: expected ‘{’ before ‘:’ token
           for (auto& [k,v] : *sent_states)
                            ^
In file included from /home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:2:0:
/opt/ros/kinetic/include/rosbag/view.h: In member function ‘void batch_ros::BagPlayer::play()’:
/opt/ros/kinetic/include/rosbag/view.h:163:5: error: ‘rosbag::View::View(const rosbag::View&)’ is private
     View(View const& view);
     ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:22: error: within this context
           for (auto& [k,v] : *sent_states)
                      ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:28: error: could not convert ‘<lambda closure object>batch_ros::BagPlayer::play()::<lambda()>{rosbag::View(v)}’ from ‘batch_ros::BagPlayer::play()::<lambda()>’ to ‘bool’
           for (auto& [k,v] : *sent_states)
                            ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:28: error: expected ‘;’ before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:28: error: expected primary-expression before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:28: error: expected ‘)’ before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:97:28: error: expected primary-expression before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:20: error: expected unqualified-id before ‘[’ token
         for (auto& [k,v] : *sent_states)
                    ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:20: error: expected ‘;’ before ‘[’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:21: error: ‘k’ was not declared in this scope
         for (auto& [k,v] : *sent_states)
                     ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp: In lambda function:
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:26: error: expected ‘{’ before ‘:’ token
         for (auto& [k,v] : *sent_states)
                          ^
In file included from /home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:2:0:
/opt/ros/kinetic/include/rosbag/view.h: In member function ‘void batch_ros::BagPlayer::play()’:
/opt/ros/kinetic/include/rosbag/view.h:163:5: error: ‘rosbag::View::View(const rosbag::View&)’ is private
     View(View const& view);
     ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:20: error: within this context
         for (auto& [k,v] : *sent_states)
                    ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:26: error: could not convert ‘<lambda closure object>batch_ros::BagPlayer::play()::<lambda()>{rosbag::View(v)}’ from ‘batch_ros::BagPlayer::play()::<lambda()>’ to ‘bool’
         for (auto& [k,v] : *sent_states)
                          ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:26: error: expected ‘;’ before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:26: error: expected primary-expression before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:26: error: expected ‘)’ before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:120:26: error: expected primary-expression before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:22: error: expected unqualified-id before ‘[’ token
           for (auto& [k,v] : *sent_states)
                      ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:22: error: expected ‘;’ before ‘[’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:23: error: ‘k’ was not declared in this scope
           for (auto& [k,v] : *sent_states)
                       ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp: In lambda function:
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:28: error: expected ‘{’ before ‘:’ token
           for (auto& [k,v] : *sent_states)
                            ^
In file included from /home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:2:0:
/opt/ros/kinetic/include/rosbag/view.h: In member function ‘void batch_ros::BagPlayer::play()’:
/opt/ros/kinetic/include/rosbag/view.h:163:5: error: ‘rosbag::View::View(const rosbag::View&)’ is private
     View(View const& view);
     ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:22: error: within this context
           for (auto& [k,v] : *sent_states)
                      ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:28: error: could not convert ‘<lambda closure object>batch_ros::BagPlayer::play()::<lambda()>{rosbag::View(v)}’ from ‘batch_ros::BagPlayer::play()::<lambda()>’ to ‘bool’
           for (auto& [k,v] : *sent_states)
                            ^
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:28: error: expected ‘;’ before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:28: error: expected primary-expression before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:28: error: expected ‘)’ before ‘:’ token
/home/ros/catkin_ws/src/batch_ros/src/bag_player_play.cpp:132:28: error: expected primary-expression before ‘:’ token
make[2]: *** [batch_ros/CMakeFiles/play_bag.dir/src/bag_player_play.cpp.o] Error 1
make[1]: *** [batch_ros/CMakeFiles/play_bag.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j16 -l16" failed
`

**Comment by protobits** [comment]
Is this on 18.04 with melodic? I can only support that version at the moment. The CMakeLists file selects the C++17 version, so it should work with that.

**Comment by royshau** [comment]
Thank you for the prompt response!

My development environment is 16.04 with Kinetic, so it might be the case.
